GET {{SwgohApi.BaseAddress}}/characters
Authorization: Bearer {{auth_token}}
###

POST {{SwgohApi.BaseAddress}}/characters
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Avar Kriss",
  "locations": ["MarqueeEvent"],
  "isAccelerated": false,
  "marquee": {
    "introductionDate": "2026-06-01",
    "marqueeEventDate": "2026-06-07",
    "shipmentDate": "2026-09-01",
    "farmDate": "2026-09-02",
    "accelerationDate": "2027-06-01"
  }
}
###

GET {{SwgohApi.BaseAddress}}/characters/2abe6d0a-52ad-4321-9d93-c65978f7ce52

###

PUT {{SwgohApi.BaseAddress}}/characters/d0b3502b-3055-4154-bb63-560c691e27a4
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "isAccelerated": true,
  "marquee": {
    "introductionDate": "2026-01-01",
    "marqueeEventDate": "2026-01-02",
    "shipmentDate": "2026-01-03",
    "farmDate": "2026-01-04",
    "accelerationDate": "2026-01-05"
  }
}

###

GET {{SwgohApi.BaseAddress}}/characters/name/Kleya%20Marki

###
