GET {{SwgohApi.BaseAddress}}/characters
Authorization: Bearer {{auth_token}}
###

POST {{SwgohApi.BaseAddress}}/characters
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "JynErso",
  "locations": ["CantinaShipments"],
  "isAccelerated": true
}
###

GET {{SwgohApi.BaseAddress}}/characters/2abe6d0a-52ad-4321-9d93-c65978f7ce52

###
