<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwgohApi.Infrastructure\SwgohApi.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ContainerRegistry>ghcr.io</ContainerRegistry>
    <ContainerImageTag>$(GITHUB_SHA)</ContainerImageTag>
  </PropertyGroup>
  <ItemGroup>
    <ContainerLabel Include="com.docker.extension.publisher-url" Value="$(GITHUB_SERVER_URL)/$(GITHUB_REPOSITORY_OWNER)" />
  </ItemGroup>
</Project>
