@SwgohApi_HostAddress = http://localhost:5149

POST {{SwgohApi_HostAddress}}/users
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "my-awesome-password"
}
###

POST {{SwgohApi_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "my-awesome-password"
}

> {%
  client.global.set("auth_token", response.body.accessToken);
  client.global.set("refresh_token", response.body.refreshToken);
%}
###

PUT {{SwgohApi_HostAddress}}/users/f3ddd778-f384-46ac-b284-8a47466bf24da
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "password": "my-awesome-password"
}
###

DELETE {{SwgohApi_HostAddress}}/users/f3ddd778-f384-46ac-b284-8a47466bf24d
Authorization: Bearer {{auth_token}}

###

POST {{SwgohApi_HostAddress}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}

> {%
  client.global.set("auth_token", response.body.accessToken);
  client.global.set("refresh_token", response.body.refreshToken);
%}
###

POST {{SwgohApi_HostAddress}}/auth/revoke
Content-Type: application/json

{
  "refreshToken": "{{refresh_token}}"
}
###

POST {{SwgohApi_HostAddress}}/auth/revoke-all
Authorization: Bearer {{auth_token}}
###

POST {{SwgohApi_HostAddress}}/characters
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Cassian Andor",
  "isAccelerated": true,
  "locations": [
    "SquadArenaShipments"
  ]
}
###

GET {{SwgohApi_HostAddress}}/characters
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###
