POST {{SwgohApi.BaseAddress}}/users
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "email": "test@example.com",
  "password": "my-awesome-password",
  "key": "e8a64643-7001-4735-899a-dd4405b56cc8"
}
###

PUT {{SwgohApi.BaseAddress}}/users/f3ddd778-f384-46ac-b284-8a47466bf24da
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "password": "my-awesome-password"
}
###

DELETE {{SwgohApi.BaseAddress}}/users/f3ddd778-f384-46ac-b284-8a47466bf24d
Authorization: Bearer {{auth_token}}
###

PUT {{SwgohApi.BaseAddress}}/users/f3ddd778-f384-46ac-b284-8a47466bf24d/updateAdmin
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "isAdmin": true
}
###
