// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SwgohApi.Infrastructure.Postgres;

#nullable disable

namespace SwgohApi.Infrastructure.Migrations
{
    [DbContext(typeof(PostgresDbContext))]
    partial class PostgresDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Character", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("IsAccelerated")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Locations")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Marquee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AccelerationDate")
                        .HasColumnType("date");

                    b.Property<string>("CharacterId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FarmDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IntroductionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("MarqueeEventDate")
                        .HasColumnType("date");

                    b.Property<string>("ShipId")
                        .HasColumnType("text");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("ShipId")
                        .IsUnique();

                    b.ToTable("Marquees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Marquee_Acceleration", "(\n    \"ShipId\" IS NULL\n)\nOR\n(\n    \"AccelerationDate\" IS NULL\n)");

                            t.HasCheckConstraint("CK_Marquee_Entity", "(\n    \"CharacterId\" IS NOT NULL\n    AND\n    \"ShipId\" IS NULL\n)\nOR\n(\n    \"CharacterId\" IS NULL\n    AND\n    \"ShipId\" IS NOT NULL\n)");
                        });
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParentTokenId")
                        .HasColumnType("text");

                    b.Property<string>("ReplacedByTokenId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "RevokedAtUtc", "ExpiresAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Ship", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Locations")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ships", (string)null);
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Marquee", b =>
                {
                    b.HasOne("SwgohApi.Infrastructure.Models.Character", "Character")
                        .WithOne("Marquee")
                        .HasForeignKey("SwgohApi.Infrastructure.Models.Marquee", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SwgohApi.Infrastructure.Models.Ship", "Ship")
                        .WithOne("Marquee")
                        .HasForeignKey("SwgohApi.Infrastructure.Models.Marquee", "ShipId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Character");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Character", b =>
                {
                    b.Navigation("Marquee");
                });

            modelBuilder.Entity("SwgohApi.Infrastructure.Models.Ship", b =>
                {
                    b.Navigation("Marquee");
                });
#pragma warning restore 612, 618
        }
    }
}
